/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegoahorcado;

import Clases.Juego;
import Clases.Jugador;
import Clases.Palabra;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author 汴雪
 */
public class Ahorcado extends javax.swing.JFrame {

    /**
     * Creates new form Ahorcado
     */
    private Jugador yo;
    private Palabra p;
    private Juego game;
    private String keyword;
    private boolean ganado;
    private ImageIcon imagen;
    private Icon fondo;
    private int contador;
            
    public Ahorcado() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        contador=0;
        imagen = new ImageIcon(getClass().getResource("/Image/Ahorcar.png"));
        fondo = new ImageIcon(imagen.getImage().getScaledInstance(dibujo.getWidth(),dibujo.getHeight(),Image.SCALE_DEFAULT));
        dibujo.setIcon(fondo);
        this.repaint();
        
        yo = new Jugador();
        p = new Palabra();
        game = new Juego();
        ganado = false;
        key.setText("");
        letra.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jugador = new javax.swing.JLabel();
        labelVida = new javax.swing.JLabel();
        vida = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        Enviar = new javax.swing.JButton();
        letra = new javax.swing.JTextField();
        labelVida1 = new javax.swing.JLabel();
        Start2 = new javax.swing.JButton();
        dibujo = new javax.swing.JLabel();
        key = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        titulo.setText("Juego Ahorcado");

        jugador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jugador.setText("Jugador");

        labelVida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVida.setText("Vida:");

        vida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        vida.setForeground(new java.awt.Color(255, 0, 51));
        vida.setText("0");

        Salir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Salir.setText("Exit");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Enviar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Enviar.setText("Play");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        letra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        letra.setText("jTextField1");

        labelVida1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVida1.setText("Introduce una letra en minuscula:");

        Start2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Start2.setText("Start Game !");
        Start2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start2ActionPerformed(evt);
            }
        });

        dibujo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        key.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        key.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Salir)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(labelVida)
                                .addGap(74, 74, 74)
                                .addComponent(vida))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(key)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(labelVida1)
                                .addGap(18, 18, 18)
                                .addComponent(letra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(Start2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jugador))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(Enviar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(dibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titulo)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jugador)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelVida)
                            .addComponent(vida))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelVida1)
                            .addComponent(letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Enviar)
                        .addGap(31, 31, 31)
                        .addComponent(key)
                        .addGap(46, 46, 46)
                        .addComponent(Start2))
                    .addComponent(dibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(Salir)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:
        char l = letra.getText().charAt(0); 
        
        ArrayList<Integer> pos = game.Play(l, p.getKey());
        char[] aux = keyword.toCharArray();
            
        if(!pos.isEmpty() && game.getVida() > 0) {
            for(int i=0;i<pos.size();i++) {
                aux[pos.get(i)] = l;
            }
            keyword = String.valueOf(aux);
            key.setText(keyword);
            
            if( keyword.equals(String.valueOf(p.getKey()))) {
                ganado = true;
            }
        }
        else{
            contador++;
            vida.setText(String.valueOf(game.getVida()));
            imagen = new ImageIcon(getClass().getResource("/Image/Ahorcar"+contador+".png"));
            fondo = new ImageIcon(imagen.getImage().getScaledInstance(dibujo.getWidth(),dibujo.getHeight(),Image.SCALE_DEFAULT));
            dibujo.setIcon(fondo);
            this.repaint();
        }
       
        if(ganado || contador == 6) {
            FinalizarPartida f = new FinalizarPartida(ganado);
            f.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_EnviarActionPerformed

    private void Start2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start2ActionPerformed
        // TODO add your handling code here:
        vida.setText(String.valueOf(game.getVida()));
        keyword = new String();
        int i = 0;
        while(i < p.getKey().length) {
            keyword += "-";
            i++;
        }
        key.setText(keyword);
        
    }//GEN-LAST:event_Start2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Start2;
    private javax.swing.JLabel dibujo;
    private javax.swing.JLabel jugador;
    private javax.swing.JLabel key;
    private javax.swing.JLabel labelVida;
    private javax.swing.JLabel labelVida1;
    private javax.swing.JTextField letra;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel vida;
    // End of variables declaration//GEN-END:variables
}
